# Site settings
title: MFC Nauen
description: Willkommen auf der Homepage des MFC Nauen e.V.
baseurl: "/"
url: "https://www.mfcnauen.de"

# Build settings
theme: minima
sass:
  style: compressed
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      header_logo: "/assets/logo.webp"
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

plugins:
  - jekyll-sitemap

exclude:
  - README.md
include:
  - assets/style.css
  - .htaccess
  - robots.txt
